# Generated by Django 6.0.7 on 2026-07-21 12:16

import django.db.models.deletion
import inspection.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=40, unique=True)),
                ('category', models.CharField(max_length=60)),
                ('subcategory', models.CharField(max_length=60)),
                ('text', models.TextField()),
                ('applies_to', models.JSONField(default=list)),
                ('active', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_number', models.CharField(max_length=15, unique=True)),
                ('customer_name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('project', models.CharField(max_length=120)),
                ('product', models.CharField(max_length=60)),
                ('tower', models.CharField(max_length=10)),
                ('unit_no', models.CharField(max_length=30)),
                ('config', models.CharField(max_length=20)),
                ('sqft', models.IntegerField()),
                ('status', models.CharField(choices=[('handover_ready', 'handover_ready'), ('not_ready', 'not_ready'), ('issues', 'issues'), ('clear', 'clear')], default='handover_ready', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=inspection.models._generate_token, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='inspection.flat')),
            ],
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('inspector', 'inspector'), ('customer', 'customer'), ('fm', 'fm')], default='inspector', max_length=20)),
                ('status', models.CharField(choices=[('in_progress', 'in_progress'), ('submitted', 'submitted')], default='in_progress', max_length=20)),
                ('inspector_name', models.CharField(blank=True, max_length=120)),
                ('inspector_contact', models.CharField(blank=True, max_length=20)),
                ('company', models.CharField(blank=True, max_length=120)),
                ('fm_name', models.CharField(blank=True, max_length=120)),
                ('fm_contact', models.CharField(blank=True, max_length=20)),
                ('inspection_date', models.DateField(blank=True, null=True)),
                ('expected_resolution_date', models.DateField(blank=True, null=True)),
                ('customer_signed', models.BooleanField(default=False)),
                ('inspector_signed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='inspection.flat')),
            ],
        ),
        migrations.CreateModel(
            name='ItemResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_key', models.CharField(max_length=40)),
                ('item_id', models.CharField(max_length=40)),
                ('response', models.CharField(blank=True, choices=[('VERIFIED', 'VERIFIED'), ('ISSUE', 'ISSUE'), ('SKIPPED', 'SKIPPED')], max_length=10, null=True)),
                ('skip_reason', models.CharField(blank=True, max_length=120)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='inspection.inspection')),
            ],
            options={
                'unique_together': {('inspection', 'room_key', 'item_id')},
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=160)),
                ('exact_location', models.TextField()),
                ('item_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='inspection.itemresponse')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='issues/')),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='inspection.issue')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40)),
                ('label', models.CharField(max_length=60)),
                ('type', models.CharField(max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='inspection.flat')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('flat', 'key')},
            },
        ),
    ]
