# Generated by Django 6.0.7 on 2026-07-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='floor_plan',
            field=models.ImageField(blank=True, null=True, upload_to='floorplans/'),
        ),
    ]
