# Generated by Django 6.0.7 on 2026-07-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0002_flat_floor_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='fixed',
            field=models.BooleanField(default=False),
        ),
    ]
