# Generated by Django 6.0.7 on 2026-07-23 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0003_issue_fixed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspection',
            name='expected_resolution_date',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='fm_contact',
        ),
        migrations.AddField(
            model_name='flat',
            name='company',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='flat',
            name='fm_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='flat',
            name='inspection_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flat',
            name='inspector_contact',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='flat',
            name='inspector_name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
