# Generated by Django 6.0.7 on 2026-07-23 06:54

from django.db import migrations, models


def rename_clear_to_handed_over(apps, schema_editor):
    Flat = apps.get_model('inspection', 'Flat')
    Flat.objects.filter(status='clear').update(status='handed_over')


def rename_handed_over_to_clear(apps, schema_editor):
    Flat = apps.get_model('inspection', 'Flat')
    Flat.objects.filter(status='handed_over').update(status='clear')


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0004_remove_inspection_expected_resolution_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='status',
            field=models.CharField(choices=[('handover_ready', 'handover_ready'), ('not_ready', 'not_ready'), ('issues', 'issues'), ('handed_over', 'handed_over')], default='handover_ready', max_length=20),
        ),
        migrations.RunPython(rename_clear_to_handed_over, rename_handed_over_to_clear),
    ]
